application:
  bindAddress: :8447
  production: false
  debug: false
database:
  address: localhost:3400
  name: inventory
  username: tradalia
  password: tradalia
authentication:
  authority: https://tradalia-server:8443/auth/realms/tradalia
  clientId: tradalia-backend
  clientSecret: xyz
platform:
  system: https://tradalia-server:8449/api/system
messaging:
  address: localhost:8450
  username: rabbit-admin
  password: rabbit.admin
provider:
  currency:
    baseUrl: https://api.freecurrencyapi.com/v1
    apiKey : YOUR_API_KEY_HERE
