application:
  bindAddress: :8447
  production: false
  debug: false
database:
  address: localhost:3400
  name: inventory
  username: bitfever
  password: bitfever
authentication:
  authority: https://bitfever-server:8443/auth/realms/bitfever
  clientId: bitfever-backend
  clientSecret: xyz
platform:
  system: https://bitfever-server:8449/api/system
messaging:
  address: localhost:8450
  username: rabbit-admin
  password: rabbit.admin
provider:
  currency:
    baseUrl: https://api.freecurrencyapi.com/v1
    apiKey : fca_live_PEgz9oUDbBGePkYR5UtVnhAU739eVYptqKvC9mTd
